
include: package:flutter_lints/flutter.yaml

linter:
  
  rules:
    avoid_print: false 
    always_declare_return_types : true
    always_use_package_imports: true
    annotate_overrides: false
    always_specify_types : false



